In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

# Librerie per il Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import LabelEncoder

In [14]:
#caricamento del dataset
df = pd.read_csv('C:\\Users\\compu\\Documents\\GitHub\\GuerraAntonia_DepositoCorso\\best-selling-manga.csv')

In [15]:
#visualizzazione delle prime righe del dataset
df.head()

,Manga series,Author(s),Publisher,Demographic,No. of collected volumes,Serialized,Approximate sales in million(s),Average sales per volume in million(s)
0,One Piece,Eiichiro Oda,Shueisha,Shōnen,104,1997–present,516.6,4.97
1,Golgo 13,"Takao Saito, Saito Production",Shogakukan,Seinen,207,1968–present,300.0,1.45
2,Case Closed / Detective Conan,Gosho Aoyama,Shogakukan,Shōnen,102,1994–present,270.0,2.65
3,Dragon Ball,Akira Toriyama,Shueisha,Shōnen,42,1984–1995,260.0,6.19
4,Doraemon,Fujiko F. Fujio,Shogakukan,Children,45,1969–1996,250.0,4.71

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Manga series                            187 non-null    object
 1   Author(s)                               187 non-null    object
 2   Publisher                               187 non-null    object
 3   Demographic                             187 non-null    object
 4   No. of collected volumes                187 non-null    int64
 5   Serialized                              187 non-null    object
 6   Approximate sales in million(s)         187 non-null    float64
 7   Average sales per volume in million(s)  187 non-null    float64
dtypes: float64(2), int64(1), object(5)
memory usage: 11.8+ KB

In [17]:
# colonna delle vendite sia numerica
df['Approximate sales in million(s)'] = pd.to_numeric(df['Approximate sales in million(s)'], errors='coerce')
print(df['Approximate sales in million(s)'].dtype)
df['No. of collected volumes'] = pd.to_numeric(df['No. of collected volumes'], errors='coerce')
print(df['No. of collected volumes'].dtype)

float64
int64

In [18]:

# Ordiniamo il dataset per vendite (dal più alto al più basso) e prendiamo i primi 15
top_manga = df.sort_values('Approximate sales in million(s)', ascending=False).head(15)
print(top_manga)

                      Manga series                      Author(s)   Publisher  \
0                        One Piece                   Eiichiro Oda    Shueisha
1                         Golgo 13  Takao Saito, Saito Production  Shogakukan
2    Case Closed / Detective Conan                   Gosho Aoyama  Shogakukan
3                      Dragon Ball                 Akira Toriyama    Shueisha
4                         Doraemon                Fujiko F. Fujio  Shogakukan
5                           Naruto              Masashi Kishimoto    Shueisha
6                        Slam Dunk                 Takehiko Inoue    Shueisha
7       KochiKame: Tokyo Beat Cops                  Osamu Akimoto    Shueisha
8   Demon Slayer: Kimetsu no Yaiba               Koyoharu Gotouge    Shueisha
9                         Oishinbo   Tetsu Kariya, Akira Hanasaki  Shogakukan
10                          Bleach                      Tite Kubo    Shueisha
11        JoJo's Bizarre Adventure                 Hirohiko Araki    Shueisha
12                 Attack on Titan                 Hajime Isayama    Kodansha
13                       Astro Boy                   Osamu Tezuka    Kobunsha
14          Fist of the North Star          Buronson, Tetsuo Hara    Shueisha

      Demographic  No. of collected volumes             Serialized  \
0          Shōnen                       104           1997–present
1          Seinen                       207           1968–present
2          Shōnen                       102           1994–present
3          Shōnen                        42              1984–1995
4        Children                        45              1969–1996
5          Shōnen                        72              1999–2014
6          Shōnen                        31              1990–1996
7          Shōnen                       201              1976–2016
8          Shōnen                        23              2016–2020
9          Seinen                       111  1983–2014 (on hiatus)
10         Shōnen                        74              2001–2016
11  Shōnen/Seinen                       131           1987–present
12         Shōnen                        34              2009–2021
13         Shōnen                        23              1952–1968
14         Shōnen                        27              1983–1988

    Approximate sales in million(s)  Average sales per volume in million(s)
0                             516.6                                    4.97
1                             300.0                                    1.45
2                             270.0                                    2.65
3                             260.0                                    6.19
4                             250.0                                    4.71
5                             250.0                                    3.47
6                             170.0                                    5.48
7                             156.5                                    0.78
8                             150.0                                    6.52
9                             135.0                                    1.22
10                            130.0                                    1.75
11                            120.0                                    0.92
12                            110.0                                    3.23
13                            100.0                                    4.35
14                            100.0                                    3.70

In [ ]:
#pulizia dei dati
#facciamo in modo di rimuovere le righe con valori mancanti nelle colonne
df = df.dropna(subset=['Approximate sales in million(s)', 'No. of collected volumes'])
df = df.reset_index(drop=True)
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Manga series                            187 non-null    object
 1   Author(s)                               187 non-null    object
 2   Publisher                               187 non-null    object
 3   Demographic                             187 non-null    object
 4   No. of collected volumes                187 non-null    int64
 5   Serialized                              187 non-null    object
 6   Approximate sales in million(s)         187 non-null    float64
 7   Average sales per volume in million(s)  187 non-null    float64
dtypes: float64(2), int64(1), object(5)
memory usage: 11.8+ KB
None
                    Manga series                      Author(s)   Publisher  \
0                      One Piece                   Eiichiro Oda    Shueisha
1                       Golgo 13  Takao Saito, Saito Production  Shogakukan
2  Case Closed / Detective Conan                   Gosho Aoyama  Shogakukan
3                    Dragon Ball                 Akira Toriyama    Shueisha
4                       Doraemon                Fujiko F. Fujio  Shogakukan

  Demographic  No. of collected volumes    Serialized  \
0      Shōnen                       104  1997–present
1      Seinen                       207  1968–present
2      Shōnen                       102  1994–present
3      Shōnen                        42     1984–1995
4    Children                        45     1969–1996

   Approximate sales in million(s)  Average sales per volume in million(s)
0                            516.6                                    4.97
1                            300.0                                    1.45
2                            270.0                                    2.65
3                            260.0                                    6.19
4                            250.0                                    4.71

In [22]:
# Funzione per pulire e convertire colonne numeriche (rimuove errori)
def clean_currency(x):
    if isinstance(x, str):
        return pd.to_numeric(x.replace(',', ''), errors='coerce')
    return x

In [24]:
# Convertiamo le colonne chiave in numeri
df['Approximate sales in million(s)'] = df['Approximate sales in million(s)'].apply(clean_currency)
df['No. of collected volumes'] = df['No. of collected volumes'].apply(clean_currency)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Manga series                            187 non-null    object
 1   Author(s)                               187 non-null    object
 2   Publisher                               187 non-null    object
 3   Demographic                             187 non-null    object
 4   No. of collected volumes                187 non-null    int64
 5   Serialized                              187 non-null    object
 6   Approximate sales in million(s)         187 non-null    float64
 7   Average sales per volume in million(s)  187 non-null    float64
dtypes: float64(2), int64(1), object(5)
memory usage: 11.8+ KB
None

In [26]:
df.head()

,Manga series,Author(s),Publisher,Demographic,No. of collected volumes,Serialized,Approximate sales in million(s),Average sales per volume in million(s)
0,One Piece,Eiichiro Oda,Shueisha,Shōnen,104,1997–present,516.6,4.97
1,Golgo 13,"Takao Saito, Saito Production",Shogakukan,Seinen,207,1968–present,300.0,1.45
2,Case Closed / Detective Conan,Gosho Aoyama,Shogakukan,Shōnen,102,1994–present,270.0,2.65
3,Dragon Ball,Akira Toriyama,Shueisha,Shōnen,42,1984–1995,260.0,6.19
4,Doraemon,Fujiko F. Fujio,Shogakukan,Children,45,1969–1996,250.0,4.71

In [ ]:
# Feature Engineering: Estraiamo l'anno di inizio dalla colonna "Serialized" (es. "1997-present" -> 1997)
def extract_year(text):
    match = re.search(r'(\d{4})', str(text))
    return int(match.group(1)) if match else np.nan

df['Start_Year'] = df['Serialized'].apply(extract_year)

In [28]:

# Gestione valori mancanti (riempiamo l'anno con la mediana e rimuoviamo righe senza vendite)
df['Start_Year'] = df['Start_Year'].fillna(df['Start_Year'].median())
df.dropna(subset=['Approximate sales in million(s)', 'No. of collected volumes'], inplace=True)

In [29]:
print(f"Dataset pulito: {df.shape[0]} righe rimanenti.")
print(df.head())

Dataset pulito: 187 righe rimanenti.
                    Manga series                      Author(s)   Publisher  \
0                      One Piece                   Eiichiro Oda    Shueisha
1                       Golgo 13  Takao Saito, Saito Production  Shogakukan
2  Case Closed / Detective Conan                   Gosho Aoyama  Shogakukan
3                    Dragon Ball                 Akira Toriyama    Shueisha
4                       Doraemon                Fujiko F. Fujio  Shogakukan

  Demographic  No. of collected volumes    Serialized  \
0      Shōnen                       104  1997–present
1      Seinen                       207  1968–present
2      Shōnen                       102  1994–present
3      Shōnen                        42     1984–1995
4    Children                        45     1969–1996

   Approximate sales in million(s)  Average sales per volume in million(s)  \
0                            516.6                                    4.97
1                            300.0                                    1.45
2                            270.0                                    2.65
3                            260.0                                    6.19
4                            250.0                                    4.71

   Start_Year
0        1997
1        1968
2        1994
3        1984
4        1969

In [30]:
#caricamento dataset pulito
df.to_csv('cleaned_manga_dataset.csv', index=False)

In [31]:
df.head()

,Manga series,Author(s),Publisher,Demographic,No. of collected volumes,Serialized,Approximate sales in million(s),Average sales per volume in million(s),Start_Year
0,One Piece,Eiichiro Oda,Shueisha,Shōnen,104,1997–present,516.6,4.97,1997
1,Golgo 13,"Takao Saito, Saito Production",Shogakukan,Seinen,207,1968–present,300.0,1.45,1968
2,Case Closed / Detective Conan,Gosho Aoyama,Shogakukan,Shōnen,102,1994–present,270.0,2.65,1994
3,Dragon Ball,Akira Toriyama,Shueisha,Shōnen,42,1984–1995,260.0,6.19,1984
4,Doraemon,Fujiko F. Fujio,Shogakukan,Children,45,1969–1996,250.0,4.71,1969

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Manga series                            187 non-null    object
 1   Author(s)                               187 non-null    object
 2   Publisher                               187 non-null    object
 3   Demographic                             187 non-null    object
 4   No. of collected volumes                187 non-null    int64
 5   Serialized                              187 non-null    object
 6   Approximate sales in million(s)         187 non-null    float64
 7   Average sales per volume in million(s)  187 non-null    float64
 8   Start_Year                              187 non-null    int64
dtypes: float64(2), int64(2), object(5)
memory usage: 13.3+ KB